#Dice Game
import random
choice=input("Enter a number between 1 and 6 :")
if choice>6:
    print "Invalid Choice"
else:
    a=(random.randint(1,6))
    print "Number generated by computer: ",a
    if choice==a:
        print "Congratulations"
    else:
        print "Better luck next time"
